# Site settings
title: Emerson Macedo
email: emerleite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Emerson Macedo - These are my thoughts on software development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://emerleite.com" # the base hostname & protocol for your site
twitter_username: emerleite
github_username:  emerleite
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
highlighter: pygments
gems:
    - jekyll-sitemap
    - jekyll-redirect-from